Disallow reporting from known VPN/proxy addresses.
xbmc-catchuptv-au/script.module.aussieaddonscommon pull request #5
Opened 2017-12-03 09:23 UTC by glennguy

Also disallow user submitted reports from overseas and known VPN/proxy
addresses

2017-12-03 10:24 UTC, andybotting requested changes
Looks good, with a few comments.

2017-12-03 10:24 UTC, andybotting commented on lib/aussieaddonscommon/utils.py
> +            xbmcgui.Dialog().ok(*message)
how about putting a 'return' right under here instead

2017-12-03 10:24 UTC, andybotting commented on lib/aussieaddonscommon/utils.py
> +def check_country(connection_info, message=None):
this function returns a bool, so would be nice to have a clear method name here like is_valid_country or valid_country?

2017-12-03 10:24 UTC, andybotting commented on lib/aussieaddonscommon/utils.py
> +    return valid_country and not blacklisted_hostname
maybe say return True here and add a return False after the blacklisted_hostname check?

2017-12-04 01:23 UTC, glennguy commented
Thanks Andy, changes made :)

2017-12-04 03:02 UTC, andybotting approved these changes

2017-12-04 03:03 UTC, merged